# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'function_ui\MainWindow_smart_room.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_smart_classroom(object):
    def setupUi(self, smart_classroom):
        smart_classroom.setObjectName("smart_classroom")
        smart_classroom.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(smart_classroom)
        self.centralwidget.setObjectName("centralwidget")
        smart_classroom.setCentralWidget(self.centralwidget)
        self.function_menu = QtWidgets.QMenuBar(smart_classroom)
        self.function_menu.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.function_menu.setObjectName("function_menu")
        self.menufunction = QtWidgets.QMenu(self.function_menu)
        self.menufunction.setObjectName("menufunction")
        self.menuexit = QtWidgets.QMenu(self.function_menu)
        self.menuexit.setObjectName("menuexit")
        self.menuabout_us = QtWidgets.QMenu(self.function_menu)
        self.menuabout_us.setObjectName("menuabout_us")
        smart_classroom.setMenuBar(self.function_menu)
        self.statusbar = QtWidgets.QStatusBar(smart_classroom)
        self.statusbar.setObjectName("statusbar")
        smart_classroom.setStatusBar(self.statusbar)
        self.face_regist = QtWidgets.QAction(smart_classroom)
        self.face_regist.setObjectName("face_regist")
        self.face_attendance = QtWidgets.QAction(smart_classroom)
        self.face_attendance.setObjectName("face_attendance")
        self.in_class = QtWidgets.QAction(smart_classroom)
        self.in_class.setObjectName("in_class")
        self.in_exam = QtWidgets.QAction(smart_classroom)
        self.in_exam.setObjectName("in_exam")
        self.action122 = QtWidgets.QAction(smart_classroom)
        self.action122.setObjectName("action122")
        self.action12 = QtWidgets.QAction(smart_classroom)
        self.action12.setObjectName("action12")
        self.in_sleep = QtWidgets.QAction(smart_classroom)
        self.in_sleep.setObjectName("in_sleep")
        self.menufunction.addAction(self.face_regist)
        self.menufunction.addAction(self.face_attendance)
        self.menufunction.addAction(self.in_class)
        self.menufunction.addAction(self.in_exam)
        self.menufunction.addAction(self.in_sleep)
        self.function_menu.addAction(self.menufunction.menuAction())
        self.function_menu.addAction(self.menuexit.menuAction())
        self.function_menu.addAction(self.menuabout_us.menuAction())

        self.retranslateUi(smart_classroom)
        QtCore.QMetaObject.connectSlotsByName(smart_classroom)

    def retranslateUi(self, smart_classroom):
        _translate = QtCore.QCoreApplication.translate
        smart_classroom.setWindowTitle(_translate("smart_classroom", "智慧教室辅助系统"))
        self.menufunction.setTitle(_translate("smart_classroom", "主要功能"))
        self.menuexit.setTitle(_translate("smart_classroom", "退出"))
        self.menuabout_us.setTitle(_translate("smart_classroom", "关于我们"))
        self.face_regist.setText(_translate("smart_classroom", "人脸注册"))
        self.face_attendance.setText(_translate("smart_classroom", "打卡"))
        self.in_class.setText(_translate("smart_classroom", "课堂行为检测"))
        self.in_exam.setText(_translate("smart_classroom", "考试行为检测"))
        self.action122.setText(_translate("smart_classroom", "122"))
        self.action12.setText(_translate("smart_classroom", "12"))
        self.in_sleep.setText(_translate("smart_classroom", "午休行为检测"))
