# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'function_test\test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.my = QtWidgets.QWidget(MainWindow)
        self.my.setObjectName("my")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.my)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 50, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.my)
        self.label.setGeometry(QtCore.QRect(200, 280, 54, 12))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.my)
        self.pushButton.setGeometry(QtCore.QRect(160, 180, 75, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.my)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menu123 = QtWidgets.QMenu(self.menubar)
        self.menu123.setObjectName("menu123")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menu123.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "nihao"))
        self.pushButton.setText(_translate("MainWindow", "123"))
        self.menu123.setTitle(_translate("MainWindow", "123"))
